apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 83.4.3
    helm:
      values: |
        grafana:
          adminPassword: "admin123"
          service:
            type: ClusterIP
          persistence:
            enabled: false

        alertmanager:
          enabled: true
          alertmanagerSpec:
            replicas: 1

        prometheus:
          prometheusSpec:
            replicas: 1
            retention: 7d
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            storageSpec: {}

        kubeStateMetrics:
          enabled: true

        nodeExporter:
          enabled: true

        prometheusOperator:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
