grafana:
  adminUser: admin
  adminPassword: admin123

  service:
    type: ClusterIP

  persistence:
    enabled: false

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1

prometheus:
  prometheusSpec:
    replicas: 1
    retention: 7d

    # 🔥 CRITICAL FIX (this solves your issue)
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true
